FROM debian:bullseye-slim
RUN apt update \
    && apt install -y openssl ca-certificates \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
COPY ./target/release/replex ./

EXPOSE 80
CMD ["/app/replex"]