# important that we build replex agains the same openssl version as the docker image
FROM debian:bookworm-slim
ARG TARGETPLATFORM
RUN apt update \
    && apt install -y openssl ca-certificates \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then \
    mv bin/x86_64-unknown-linux-gnu/replex app/replex && \
    chmod +x app/replex && \
    ls -la app/ . && \
    pwd \
    ; fi
    
RUN if [ "${TARGETPLATFORM}" = "linux/arm64" ]; then \
    mv bin/aarch64-unknown-linux-gnu/replex app/replex && \
    chmod +x app/replex && \
    ls -la app/ . && \
    pwd \
    ; fi

# RUN if [ "${TARGETPLATFORM}" = "linux/arm/v7" ]; then \
#     mv bin/armhf-bin/dim app/replex && \
#     chmod +x app/replex && \
#     ls -la app/ . && \
#     pwd \
#     ; fi
# COPY ./ci-target/release/replex ./

EXPOSE 80
CMD ["/app/replex"]
