# important that we build replex agains the same openssl version as the docker image
FROM debian:bookworm-slim
RUN apt update \
    && apt install -y openssl ca-certificates \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app
COPY ./ci-target/release/replex ./

EXPOSE 80
CMD ["/app/replex"]
